parameters:
#    tickets_suport.example.class: Tickets\SuportBundle\Example

services:
#    tickets_suport.example:
#        class: %tickets_suport.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
